title: VGG.CZ
email: me@vgg.cz

description: >- # this means to ignore newlines until "baseurl:"
  My personal website.
baseurl: ""
url: "https://vgg.cz"

github_username:  vvveracruz
repo: https://github.com/vvveracruz/vvveracruz.github.io

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# build settings

permalink: /:title
sass:
  sass_dir: /assets/css/

markdown: kramdown
highlighter: rouge
