title: VGG.CZ
email: me@vgg.cz
description: >- # this means to ignore newlines until "baseurl:"
  My personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vgg.cz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vvveracruz
github_username:  vvveracruz

permalink: /:title

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
